### ISSUE TITLE
Background colors

### ISSUE THREAD

**Issue by Rodrigap** [jchabot87/Dasmotos#3]
https://github.com/jchabot87/Dasmotos/blob/034759effb933a1221f10a8bcb1796c0c847de86/style.css#L24-L26

It looks like your background colors didn't show up! I'd recommend simply giving each h2 a class name, like "brushes-title", and giving that class a background color.

**Comment by jchabot87** [comment]
That is strange, they showed up fine on my PC but thanks for the tip!
